/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const Logo = () => {
  return (
    <LogoContainer>
      <LogoIcon
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e1a0ffcf174e5324de0e7b3b3dfc2187de6a0487a332e86245e26ebe1225cdf?placeholderIfAbsent=true&apiKey=f96fe59b591041bf9b3db6ad20182335"
        alt="Logo Icon"
      />
      <LogoText
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bf433a7a6ab9125a77e6e1e3c55168747e705f825f21c8425ab49ef8097aac27?placeholderIfAbsent=true&apiKey=f96fe59b591041bf9b3db6ad20182335"
        alt="Logo Text"
      />
    </LogoContainer>
  );
};

const LogoContainer = styled.div`
  display: flex;
  align-items: center;
  gap: 5px;
`;

const LogoIcon = styled.img`
  width: 43px;
  height: 43px;
  object-fit: contain;
`;

const LogoText = styled.img`
  width: 115px;
  height: 35px;
  object-fit: contain;
`;

export default Logo;
