/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const MetricWidget = ({ value, title, description }) => {
  return (
    <WidgetContainer>
      {value && <MetricValue>{value}</MetricValue>}
      {title && <MetricTitle>{title}</MetricTitle>}
      <MetricDescription>{description}</MetricDescription>
    </WidgetContainer>
  );
};

const WidgetContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border-radius: 8px;
  border: 1px solid var(--Gray-100, #36434e);
  background: var(--Cards, #001d31);
  padding: 24px;
  margin-top: 41px;
  min-height: 128px;
  color: var(--White, #fff);
  text-align: center;
  font-family: Inter, sans-serif;

  @media (max-width: 991px) {
    margin-top: 40px;
    padding: 20px;
  }
`;

const MetricValue = styled.div`
  font-size: 36px;
  font-weight: 600;
  line-height: 1;
`;

const MetricTitle = styled.h3`
  font-size: 24px;
  font-weight: 600;
  line-height: 1;
  margin: 0;
`;

const MetricDescription = styled.p`
  font-size: 16px;
  font-weight: 400;
  line-height: 24px;
  margin-top: 7px;
`;

export default MetricWidget;
