/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const chartData = [
  { title: "Technology and equip...", percentage: "10.33%", color: "#9747ff" },
  { title: "Marketing", percentage: "4.19%", color: "#fca997" },
  { title: "Finance", percentage: "10.33%", color: "#b91293" },
  { title: "Human Resources", percentage: "4.19%", color: "#c3e1ff" },
  { title: "Marketing", percentage: "10.33%", color: "#fb4e22" },
  { title: "Design", percentage: "4.19%", color: "#f3a8e2" },
  { title: "QA Analyst", percentage: "10.33%", color: "#ffd7a3" },
];

const TotalImprovementChart = () => {
  return (
    <ChartContainer>
      <ChartTitle>
        <h2>Total Improvement</h2>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0a8a2297ec032c0eb2c7c69719864b7f5a2a5fc9394db7728731d9692b082939?placeholderIfAbsent=true&apiKey=f96fe59b591041bf9b3db6ad20182335"
          alt="Chart"
        />
      </ChartTitle>
      <DataDetails>
        <h3>Job Titles</h3>
        {chartData.map((item, index) => (
          <DataItem key={index}>
            <ItemContent>
              <ColorDot color={item.color} />
              <span>{item.title}</span>
            </ItemContent>
            <Percentage>{item.percentage}</Percentage>
          </DataItem>
        ))}
      </DataDetails>
    </ChartContainer>
  );
};

const ChartContainer = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border-radius: 8px;
  border: 1px solid var(--Gray-100, #36434e);
  background: var(--Cards, #001d31);
  padding: 40px;
  min-height: 923px;
  color: var(--White, #fff);
  font-family: Inter, sans-serif;
  @media (max-width: 991px) {
    margin-top: 40px;
    padding: 20px;
  }
`;

const ChartTitle = styled.div`
  align-self: stretch;
  h2 {
    font-size: 16px;
    font-weight: 600;
    margin-bottom: 22px;
  }
  img {
    width: 100%;
    max-width: 489px;
    height: auto;
  }
`;

const DataDetails = styled.div`
  align-self: stretch;
  margin-top: 40px;
  h3 {
    font-size: 16px;
    font-weight: 600;
    margin-bottom: 16px;
  }
`;

const DataItem = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  font-size: 12px;
`;

const ItemContent = styled.div`
  display: flex;
  align-items: center;
  gap: 16px;
`;

const ColorDot = styled.div`
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background-color: ${(props) => props.color};
`;

const Percentage = styled.span`
  font-weight: 400;
`;

export default TotalImprovementChart;
